# Generated by Django 3.1.4 on 2022-03-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='memes')),
                ('top_text', models.TextField(max_length=500)),
                ('bottom_text', models.TextField(max_length=500)),
            ],
        ),
    ]
