# Generated by Django 3.1.4 on 2022-03-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='bottom_text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='memes',
            name='top_text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
